language: objective-c
osx_image: xcode8.3
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - pod install --project-directory=Example
before_script:
  - export LANG=en_US.UTF-8
script:
- set -o pipefail && xcodebuild test -workspace Example/TouchAnimationView.xcworkspace -scheme TouchAnimationView-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
